# Nom de ton application Spring Boot
spring.application.name=ApiCollabDev

# Configuration BDD MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/collabdev_db
spring.datasource.username=root
spring.datasource.password=00223baba
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate : créer / mettre à jour le schéma automatiquement
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL dans la console (bonne syntaxe !)
spring.jpa.show-sql=true
